//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAccount
    {
        public int AdminID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
        public Nullable<int> IsLocked { get; set; }
    }
}
