//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceReport
    {
        public int ID { get; set; }
        public string Device { get; set; }
        public int AmountDevice { get; set; }
        public string CreateDate { get; set; }
        public int RoomId { get; set; }
        public string ReportStatus { get; set; }
        public string Description { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
