//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.StudentAccounts = new HashSet<StudentAccount>();
        }
    
        public int RoomID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public string Name { get; set; }
        public string RoomType { get; set; }
        public int MaxCapacity { get; set; }
        public Nullable<int> Occupancy { get; set; }
        public string Status { get; set; }
        public string Gender { get; set; }
        public string Descript { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAccount> StudentAccounts { get; set; }
    }
}
