//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int ID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Number { get; set; }
        public int Hide { get; set; }
    }
}
