//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryManagement.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Web;

	public partial class StudentAccount
	{
		public int StudentID { get; set; }
		public string UserName { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string ImagePath { get; set; }

		[NotMapped]
		public HttpPostedFileBase ImageFile { get; set; }



		public Nullable<int> RoomID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
        public Nullable<int> IsLocked { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Room Room { get; set; }
    }
}
